### ISSUE TITLE
make_instance.py  has an error

### ISSUE THREAD

**Issue by huangleitaoICT** [tzt101/INADE#2]
when i run the code "make_instance.py"    in the mode ade_20k   
it occurs an error   in  line 102  with 
"RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Long for the source"

运行制作实力分割的代码"make_instance.py"时  用ade_20k模式  在102行报错
        tmp[tmp==ori_idx[idx]] = new_idx[idx]
这行代码报错信息如下：
"RuntimeError: Index put requires the source and destination dtypes match, got Float for the destination and Long for the source"

这是我第一次提交错误信息 格式如有不对还望海涵

**Comment by huynhbaobk** [comment]
I got same error

**Comment by tzt101** [comment]
Hi, I have updated the code for make_instance.py. It has been tested on python3.6.
