### ISSUE TITLE
Save "IE" net in checkpoint

### ISSUE THREAD

**Issue by huynhbaobk** [tzt101/INADE#3]
I got the error when using --continue_train
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/bao_test/latest_net_IE.pth'

I think the save network should be "IE" if "inade" ? Thanks 
<img width="482" alt="Screen Shot 2021-10-16 at 22 26 33" src="https://user-images.githubusercontent.com/30063610/137593272-15d4d5c5-d807-42fd-9078-083cc8db32ae.png">

**Comment by tzt101** [comment]
Thank your for pointing out it. I have change the encoder init name from "IE" to "E" (line 134 in models/pix2pix_model.py) to keep it consistent.
