### ISSUE TITLE
A problem related to the implementation of feature matching loss

### ISSUE THREAD

**Issue by lizijue** [tzt101/INADE#5]
Thanks for your excellent work!

I would like to ask a question about the feature matching loss when sepcifying "inade"  in configuration. To be specific, what is the reason for only considering the intermediate feature maps starting from layer 3, while discarding the previous features?

![QQ截图20230614164525](https://github.com/tzt101/INADE/assets/45393123/465cc0c8-5f43-4b28-9a96-c3315ce89ebf)

> in pix2pix_model.py

Looking forward to your reply.

**Comment by tzt101** [comment]
Hi, it is mainly used to reduce the ambiguity during training since the random noise input corresponding to the same GT image. If all features are used, the diversity of generator may be reduced.

**Comment by lizijue** [comment]
I understand it. Thanks for your patient explanation.
